### ISSUE TITLE
01. 신뢰할 수 있고 확장 가능하며 유지보수하기 쉬운 애플리케이션

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#1]
- Sub Chapter 
    - 데이터 시스템에 대한 생각
    - 신뢰성
    - 확장성
    - 유지보수성
- 만료일 : 2022-12-03

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by wlsdnjs829** [comment]
https://jinwon829.notion.site/b3d236fbccc74621b056c6000cbd1ffe 1장 정리 링크

**Comment by catsbi** [comment]
1장 정리 링크 [[link]](https://catsbi.oopy.io/78b397fd-cead-401c-aa71-7bdc30b867d4)

**Comment by yujeongJeon** [comment]
1장 정리
https://newjeong-dev.notion.site/01-649b4beccf7342179ffcc221f1d885c7

**Comment by DevRunner21** [comment]
[노션정리](https://devrunner21.notion.site/1-51887269f50d457581df22a046cabad1)
