### ISSUE TITLE
09. 일관성과 합의(2/2)

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#10]
- Sub Chapter 
    - 분산 트랜잭션과 합의
        - 원자적 커밋과 2단계 커밋(2PC)
        - 현실의 분산 트랜잭션
        - 내결함성을 지닌 합의
        - 멤버십과 코디네이션 서비스
- 만료일 : 2023-03-05

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by wlsdnjs829** [comment]
[[일관성과 합의 (2/2)]](https://jinwon829.notion.site/341659a42635481d82b60d99f879a9cb)
금주는 가족 모임으로 인해 불참입니다. 양해해 주셔서 감사합니다🙇🏽‍♂️

**Comment by DevRunner21** [comment]
[일관성과 합의(2/2)](https://devrunner21.notion.site/9-2197b94f71454e9bae4b83a7510d8b7d)

**Comment by yujeongJeon** [comment]
[일관성과 합의 (2/2)](https://newjeong-dev.notion.site/09-332cacdae44e4be0ad3120cb89fb2d52)

**Comment by catsbi** [comment]
[일관성과 합의(2/2)](https://catsbi.oopy.io/79c4ab28-2130-4132-90b2-10076372a573#6bc64e5f-6133-4d19-8aaf-1fda11c9f66e)
