### ISSUE TITLE
10. 일괄 처리 

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#11]
- Sub Chapter 
    - 유닉스 도구로 일괄 처리하기
        - 단순 로그 분석
        - 유닉스 철학
    - 맵리듀스와 분산 파일 시스템
        - 맵리듀스 작업 실행하기
        - 리듀스 사이드 조인과 그룹화
        - 맵 사이드 조인
    
- 만료일 : 2023-03-26

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by DevRunner21** [comment]
[일괄처리1/2](https://www.notion.so/devrunner21/10-4e58abb42d1f4a7c9b0fe37fb7ffeeb9?pvs=4)

**Comment by yujeongJeon** [comment]
[일괄처리](https://newjeong-dev.notion.site/10-9b40162c0d8243b9afa84ddd6e55a761)

**Comment by catsbi** [comment]
[일괄처리](https://catsbi.oopy.io/27f31115-ed19-46af-ab4b-1ca4bc6e9a79)
