### ISSUE TITLE
02. 데이터 모델과 질의 언어

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#2]
- Sub Chapter 
    - 관계형 모델과 문서 모델
    - 데이터를 위한 질의 언어
    - 그래프형 데이터 모델
- 만료일 : 2022-12-03

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by wlsdnjs829** [comment]
https://jinwon829.notion.site/3dc07ddb578849cab3902031a566d873 2장 정리 노션 링크

**Comment by yujeongJeon** [comment]
2장 정리
https://newjeong-dev.notion.site/02-32b5468c61da47589678ea569d99c434

**Comment by catsbi** [comment]
2장 정리 [[링크]](https://catsbi.oopy.io/f7bea257-8ffc-460b-a2da-4d9197f73504)

**Comment by DevRunner21** [comment]
[노션링크](https://www.notion.so/devrunner21/2-b388d7a8f9d240968f10a09399f7a326)
