### ISSUE TITLE
04. 부호화와 발전

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#4]
- Sub Chapter 
    - 데이터 부호화 형식
        - 언어별 형식
        - JSON과 XML, 이진 변형
        - 스리프트와 프로토콜 버퍼
        - 아브로
        - 스키마의 장점 
    - 데이터플로 모드
        - 데이터베이스를 통한 데이터플로
        - 서비스를 통한 데이터플로: REST와 RPC
        - 메시지 전달 데이터플로 
    
- 만료일 : 2023-01-01 (일요일)

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by wlsdnjs829** [comment]
재밌었던 챕터, 어려웠던 챕터들에 비해 조금 많이 아는 분야가 있어서 그런 걸 수도 있을 거 같아요.
**[정리 링크](https://jinwon829.notion.site/6702999013e54db1ac706db27aa6f541)**

**Comment by catsbi** [comment]
아 슬슬 빡세요 빡세~

4장 부호화와 발전 [[링크](https://catsbi.oopy.io/5a43e5ed-7aad-4077-8b1a-bd221eef3b36)]

**Comment by yujeongJeon** [comment]
[4장 정리](https://www.notion.so/newjeong-dev/04-572e3b1ca21e4b5f9b1de4266d8afc96)

**Comment by DevRunner21** [comment]
[4장 정리](https://www.notion.so/devrunner21/4-bffbe166923742b88912cc965f054c71)
