### ISSUE TITLE
05. 복제

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#5]
- Sub Chapter 
    - 리더와 팔로워
    - 복제 지연 문제
    - 다중 리더 복제
    - 리더 없는 복제
    
- 만료일 :  2023-01-08

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by wlsdnjs829** [comment]
[정리 링크](https://jinwon829.notion.site/2410f61724b94253a5aea7ccc47ef63c)
국어책 읽듯이..😥

**Comment by catsbi** [comment]
코로나와 함께하는 5장이였네요. 양도 많아서 힘들었던 것 같습니다. 
[[링크]](https://catsbi.oopy.io/c71c955c-6aa5-452d-93e6-b8fcadcdcba0)

**Comment by yujeongJeon** [comment]
[5장 정리](https://newjeong-dev.notion.site/05-e21dca727dce4b0db8a79a8936132ca0) 정족수 어렵네요 ..ㅠ

**Comment by DevRunner21** [comment]
[5장 정리](https://devrunner21.notion.site/5-dccf3c365fb1430bbe5248c0c13b9329)
