### ISSUE TITLE
06. 파티셔닝

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#6]
- Sub Chapter 
    - 파티셔닝과 복제
    - 키-값 데이터 파티셔닝
    - 파티셔닝과 보조 색인
    - 파티션 재균형화
    - 요청 라우팅 
    
- 만료일 : 2023-01-15

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by wlsdnjs829** [comment]
짧아서 행복했습니다.
**[파티셔닝 정리](https://www.notion.so/jinwon829/111da0f8af0d4c22962ea9acc68acbd3)**

**Comment by yujeongJeon** [comment]
[6장 정리](https://newjeong-dev.notion.site/06-d3bdfd4f960c487397564723b0022bad)

**Comment by catsbi** [comment]
스프링 배치 인강본다고 마지막 챕터 포스팅이 늦었습니다... 
[[6장 링크]](https://catsbi.oopy.io/5f556840-f956-4602-90c0-6bc97b0213a7)

**Comment by DevRunner21** [comment]
[6장 정리](https://devrunner21.notion.site/6-b22e8e5b78384ff69dad47e8dea26035)
