### ISSUE TITLE
09. 일관성과 합의 [1/2]

### ISSUE THREAD

**Issue by catsbi** [devbook-study/designing-data-intensive-applications#9]
- Sub Chapter 
    - 일관성 보장
    - 선형성
        - 시스템에 선형성을 부여하는 것은 무엇인가?
        - 선형성에 기대기
        - 선형성 시스템 구현하기
        - 선형성의 비용
    - 순서화 보장
        -  순서화와 인과성
        - 일련번호 순서화
        - 전체 순서 브로드캐스트
    
- 만료일 : 2023-02-26

정리한 자료를 업로드 혹은 링크를 코멘트로 남겨주세요. 👍

**Comment by wlsdnjs829** [comment]
[[1/2 링크]](https://jinwon829.notion.site/341659a42635481d82b60d99f879a9cb)

**Comment by yujeongJeon** [comment]
[9장 정리 (~순서화)](https://newjeong-dev.notion.site/09-332cacdae44e4be0ad3120cb89fb2d52)

**Comment by DevRunner21** [comment]
[9장 정리](https://www.notion.so/devrunner21/9-2197b94f71454e9bae4b83a7510d8b7d?pvs=4)

**Comment by catsbi** [comment]
[[9장 정리](79c4ab28-2130-4132-90b2-10076372a573)]

**Comment by wlsdnjs829** [comment]
2/2 열어주세요 방장님

**Comment by catsbi** [comment]
@wlsdnjs829  열었습니다~
